[workspace]
resolver = "2"

members = [
    "numbat",
    "numbat-exchange-rates",
    "numbat-cli",
    "numbat-jupyter-kernel",
]

exclude = [
    "numbat-wasm"
]

[profile.release]
lto = true
strip = true
codegen-units = 1
